package com.example.ward;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
@SpringBootApplication
@MapperScan("com.example.ward.Dao")
public class WardApplication {

    public static void main(String[] args) {
        SpringApplication.run(WardApplication.class, args);
    }

}
